config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

resources :users
resources :sessions
delete '/logout' => 'sessions#destroy', as: :logout

namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    authenticates_with_sorcery!

attr_accessor :password, :password_confirmation
validates_presence_of :email, message: "邮箱不能为空"
validates_format_of :email, message: "邮箱格式不合法",
with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
if: proc { |user| !user.email.blank? }
validates :email, uniqueness: true

validates_presence_of :password, message: "密码不能为空",
if: :need_validate_password
validates_presence_of :password_confirmation, message: "密码确认不能为空",
if: :need_validate_password
validates_confirmation_of :password, message: "密码不一致",
if: :need_validate_password
validates_length_of :password, message: "密码最短为6位", minimum: 6,
if: :need_validate_password

def username
  self.email.split('@').first
end

private
def need_validate_password
  self.new_record? ||
    (!self.self.password.nir?||!self.password_confirmation.nir?)
end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base

layout  'admin/layouts/admin'

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController 
  def index
  end

  def new
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController 
  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user =User.new
    end
    
    def create
        @user = User.new(params.require(:user)
        .permit(:email, :password, :password_confirmation))
        
        if @user.save
            flash[:notice] = "注册成功，请登录"
            redirect_to new_session_path
          else
            render action: :new
        end
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin::Categories#index</h1>
<p>Find me in app/views/admin/categories/index.html.erb</p>

app/views/admin/categories/new.html.erb
<h1>Admin::Categories#new</h1>
<p>Find me in app/views/admin/categories/new.html.erb</p>

app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= admin_categories_path %>">分类</a></li>
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理平台-米奇妙妙屋</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
  <%= render 'admin/layouts/menu' %>

  <div class="container">
  <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end -%>

    <%= yield %>
    </div>

    <%= javascript_include_tag 'admin' %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterRailsByActions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>